import { EngineConfigurationOption, Text } from '@sonolus/core'

export const optionsDefinition = {
    speed: {
        name: Text.Speed,
        standard: true,
        advanced: true,
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    hidden: {
        name: Text.Hidden,
        standard: true,
        advanced: true,
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    noteSpeed: {
        name: Text.NoteSpeed,
        scope: 'Our Notes',
        type: 'slider',
        // MasterOptionDefault preset 1 stores the fresh-user value 5.00.
        // MasterLiveSettings.note_speed_default=6 is only the runtime
        // fallback used when no persisted option is available.
        def: 5,
        min: 1,
        max: 12,
        step: 0.01,
    },
    guidelineCount: {
        name: 'Guideline Count',
        scope: 'Our Notes',
        type: 'select',
        // MasterOptionDefault GuidelineCount=2 -> LiveLaneSplitCountType.Lane6.
        def: 2,
        values: ['None', '4', '6', '8', '12'],
    },
    guidelineOpacity: {
        name: 'Guideline Opacity',
        scope: 'Our Notes',
        type: 'slider',
        def: 0.4,
        min: 0,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    laneOpacity: {
        name: 'Lane Opacity',
        scope: 'Our Notes',
        type: 'slider',
        def: 0.8,
        min: 0,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    showJudgmentLine: {
        name: 'Judgment Line',
        scope: 'Our Notes',
        type: 'toggle',
        // MasterOptionDefault JudgePositionDisplay is false in every preset.
        def: 0,
    },
    mirror: {
        name: Text.Mirror,
        type: 'toggle',
        def: 0,
    },
    sfxEnabled: {
        name: Text.Effect,
        scope: 'Our Notes',
        type: 'toggle',
        def: 1,
    },
    autoSFX: {
        name: Text.EffectAuto,
        scope: 'Our Notes',
        type: 'toggle',
        def: 0,
    },
    noteEffectEnabled: {
        name: Text.NoteEffect,
        scope: 'Our Notes',
        type: 'toggle',
        def: 1,
    },
    noteEffectSize: {
        name: Text.NoteEffectSize,
        scope: 'Our Notes',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    markerAnimation: {
        name: Text.MarkerAnimation,
        scope: 'Our Notes',
        type: 'toggle',
        def: 1,
    },
    simLineEnabled: {
        name: Text.Simline,
        scope: 'Our Notes',
        type: 'toggle',
        def: 1,
    },
    connectorAlpha: {
        name: Text.ConnectorAlpha,
        scope: 'Our Notes',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    laneEffectEnabled: {
        name: Text.LaneEffect,
        scope: 'Our Notes',
        type: 'toggle',
        def: 1,
    },
    lockStageAspectRatio: {
        name: Text.StageAspectratioLock,
        scope: 'Our Notes',
        type: 'toggle',
        def: 1,
    },
    previewVerticalScale: {
        name: Text.PreviewScaleVertical,
        scope: 'Our Notes',
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    previewMeasure: {
        name: Text.PreviewMeasure,
        scope: 'Our Notes',
        type: 'toggle',
        def: 1,
    },
    previewBeat: {
        name: Text.PreviewBeat,
        scope: 'Our Notes',
        type: 'toggle',
        def: 1,
    },
    previewTime: {
        name: Text.PreviewTime,
        scope: 'Our Notes',
        type: 'toggle',
        def: 1,
    },
    previewBpm: {
        name: Text.PreviewBpm,
        scope: 'Our Notes',
        type: 'toggle',
        def: 1,
    },
    previewTimeScale: {
        name: Text.PreviewTimescale,
        scope: 'Our Notes',
        type: 'toggle',
        def: 1,
    },
} satisfies Record<string, EngineConfigurationOption>
