// Generated by scripts/generate-native-note-geometry.ts.

export const nativeNoteCapSprites = {
    nativeTapLeft0: 'Our Notes Native Tap Left 0',
    nativeTapLeft1: 'Our Notes Native Tap Left 1',
    nativeTapLeft2: 'Our Notes Native Tap Left 2',
    nativeTapLeft3: 'Our Notes Native Tap Left 3',
    nativeTapLeft4: 'Our Notes Native Tap Left 4',
    nativeTapLeft5: 'Our Notes Native Tap Left 5',
    nativeTapLeft6: 'Our Notes Native Tap Left 6',
    nativeTapRight0: 'Our Notes Native Tap Right 0',
    nativeTapRight1: 'Our Notes Native Tap Right 1',
    nativeTapRight2: 'Our Notes Native Tap Right 2',
    nativeTapRight3: 'Our Notes Native Tap Right 3',
    nativeTapRight4: 'Our Notes Native Tap Right 4',
    nativeTapRight5: 'Our Notes Native Tap Right 5',
    nativeTapRight6: 'Our Notes Native Tap Right 6',
    nativeSlideLeft0: 'Our Notes Native Slide Left 0',
    nativeSlideLeft1: 'Our Notes Native Slide Left 1',
    nativeSlideLeft2: 'Our Notes Native Slide Left 2',
    nativeSlideLeft3: 'Our Notes Native Slide Left 3',
    nativeSlideLeft4: 'Our Notes Native Slide Left 4',
    nativeSlideLeft5: 'Our Notes Native Slide Left 5',
    nativeSlideLeft6: 'Our Notes Native Slide Left 6',
    nativeSlideRight0: 'Our Notes Native Slide Right 0',
    nativeSlideRight1: 'Our Notes Native Slide Right 1',
    nativeSlideRight2: 'Our Notes Native Slide Right 2',
    nativeSlideRight3: 'Our Notes Native Slide Right 3',
    nativeSlideRight4: 'Our Notes Native Slide Right 4',
    nativeSlideRight5: 'Our Notes Native Slide Right 5',
    nativeSlideRight6: 'Our Notes Native Slide Right 6',
    nativeEndLeft0: 'Our Notes Native End Left 0',
    nativeEndLeft1: 'Our Notes Native End Left 1',
    nativeEndLeft2: 'Our Notes Native End Left 2',
    nativeEndLeft3: 'Our Notes Native End Left 3',
    nativeEndLeft4: 'Our Notes Native End Left 4',
    nativeEndLeft5: 'Our Notes Native End Left 5',
    nativeEndLeft6: 'Our Notes Native End Left 6',
    nativeEndRight0: 'Our Notes Native End Right 0',
    nativeEndRight1: 'Our Notes Native End Right 1',
    nativeEndRight2: 'Our Notes Native End Right 2',
    nativeEndRight3: 'Our Notes Native End Right 3',
    nativeEndRight4: 'Our Notes Native End Right 4',
    nativeEndRight5: 'Our Notes Native End Right 5',
    nativeEndRight6: 'Our Notes Native End Right 6',
    nativeFlickLeft0: 'Our Notes Native Flick Left 0',
    nativeFlickLeft1: 'Our Notes Native Flick Left 1',
    nativeFlickLeft2: 'Our Notes Native Flick Left 2',
    nativeFlickLeft3: 'Our Notes Native Flick Left 3',
    nativeFlickLeft4: 'Our Notes Native Flick Left 4',
    nativeFlickLeft5: 'Our Notes Native Flick Left 5',
    nativeFlickLeft6: 'Our Notes Native Flick Left 6',
    nativeFlickRight0: 'Our Notes Native Flick Right 0',
    nativeFlickRight1: 'Our Notes Native Flick Right 1',
    nativeFlickRight2: 'Our Notes Native Flick Right 2',
    nativeFlickRight3: 'Our Notes Native Flick Right 3',
    nativeFlickRight4: 'Our Notes Native Flick Right 4',
    nativeFlickRight5: 'Our Notes Native Flick Right 5',
    nativeFlickRight6: 'Our Notes Native Flick Right 6',
    nativeFlickLeftLeft0: 'Our Notes Native FlickLeft Left 0',
    nativeFlickLeftLeft1: 'Our Notes Native FlickLeft Left 1',
    nativeFlickLeftLeft2: 'Our Notes Native FlickLeft Left 2',
    nativeFlickLeftLeft3: 'Our Notes Native FlickLeft Left 3',
    nativeFlickLeftLeft4: 'Our Notes Native FlickLeft Left 4',
    nativeFlickLeftLeft5: 'Our Notes Native FlickLeft Left 5',
    nativeFlickLeftLeft6: 'Our Notes Native FlickLeft Left 6',
    nativeFlickLeftRight0: 'Our Notes Native FlickLeft Right 0',
    nativeFlickLeftRight1: 'Our Notes Native FlickLeft Right 1',
    nativeFlickLeftRight2: 'Our Notes Native FlickLeft Right 2',
    nativeFlickLeftRight3: 'Our Notes Native FlickLeft Right 3',
    nativeFlickLeftRight4: 'Our Notes Native FlickLeft Right 4',
    nativeFlickLeftRight5: 'Our Notes Native FlickLeft Right 5',
    nativeFlickLeftRight6: 'Our Notes Native FlickLeft Right 6',
    nativeFlickRightLeft0: 'Our Notes Native FlickRight Left 0',
    nativeFlickRightLeft1: 'Our Notes Native FlickRight Left 1',
    nativeFlickRightLeft2: 'Our Notes Native FlickRight Left 2',
    nativeFlickRightLeft3: 'Our Notes Native FlickRight Left 3',
    nativeFlickRightLeft4: 'Our Notes Native FlickRight Left 4',
    nativeFlickRightLeft5: 'Our Notes Native FlickRight Left 5',
    nativeFlickRightLeft6: 'Our Notes Native FlickRight Left 6',
    nativeFlickRightRight0: 'Our Notes Native FlickRight Right 0',
    nativeFlickRightRight1: 'Our Notes Native FlickRight Right 1',
    nativeFlickRightRight2: 'Our Notes Native FlickRight Right 2',
    nativeFlickRightRight3: 'Our Notes Native FlickRight Right 3',
    nativeFlickRightRight4: 'Our Notes Native FlickRight Right 4',
    nativeFlickRightRight5: 'Our Notes Native FlickRight Right 5',
    nativeFlickRightRight6: 'Our Notes Native FlickRight Right 6',
    nativeTraceLeft0: 'Our Notes Native Trace Left 0',
    nativeTraceLeft1: 'Our Notes Native Trace Left 1',
    nativeTraceLeft2: 'Our Notes Native Trace Left 2',
    nativeTraceLeft3: 'Our Notes Native Trace Left 3',
    nativeTraceLeft4: 'Our Notes Native Trace Left 4',
    nativeTraceLeft5: 'Our Notes Native Trace Left 5',
    nativeTraceLeft6: 'Our Notes Native Trace Left 6',
    nativeTraceRight0: 'Our Notes Native Trace Right 0',
    nativeTraceRight1: 'Our Notes Native Trace Right 1',
    nativeTraceRight2: 'Our Notes Native Trace Right 2',
    nativeTraceRight3: 'Our Notes Native Trace Right 3',
    nativeTraceRight4: 'Our Notes Native Trace Right 4',
    nativeTraceRight5: 'Our Notes Native Trace Right 5',
    nativeTraceRight6: 'Our Notes Native Trace Right 6',
    nativeNodeLeft0: 'Our Notes Native Node Left 0',
    nativeNodeLeft1: 'Our Notes Native Node Left 1',
    nativeNodeLeft2: 'Our Notes Native Node Left 2',
    nativeNodeLeft3: 'Our Notes Native Node Left 3',
    nativeNodeLeft4: 'Our Notes Native Node Left 4',
    nativeNodeLeft5: 'Our Notes Native Node Left 5',
    nativeNodeLeft6: 'Our Notes Native Node Left 6',
    nativeNodeRight0: 'Our Notes Native Node Right 0',
    nativeNodeRight1: 'Our Notes Native Node Right 1',
    nativeNodeRight2: 'Our Notes Native Node Right 2',
    nativeNodeRight3: 'Our Notes Native Node Right 3',
    nativeNodeRight4: 'Our Notes Native Node Right 4',
    nativeNodeRight5: 'Our Notes Native Node Right 5',
    nativeNodeRight6: 'Our Notes Native Node Right 6',
    nativeTapMainLeft: 'Our Notes Native Tap Main Left',
    nativeTapMainMiddle: 'Our Notes Native Tap Main Middle',
    nativeTapMainRight: 'Our Notes Native Tap Main Right',
    nativeSlideMainLeft: 'Our Notes Native Slide Main Left',
    nativeSlideMainMiddle: 'Our Notes Native Slide Main Middle',
    nativeSlideMainRight: 'Our Notes Native Slide Main Right',
    nativeEndMainLeft: 'Our Notes Native End Main Left',
    nativeEndMainMiddle: 'Our Notes Native End Main Middle',
    nativeEndMainRight: 'Our Notes Native End Main Right',
    nativeFlickMainLeft: 'Our Notes Native Flick Main Left',
    nativeFlickMainMiddle: 'Our Notes Native Flick Main Middle',
    nativeFlickMainRight: 'Our Notes Native Flick Main Right',
    nativeFlickLeftMainLeft: 'Our Notes Native FlickLeft Main Left',
    nativeFlickLeftMainMiddle: 'Our Notes Native FlickLeft Main Middle',
    nativeFlickLeftMainRight: 'Our Notes Native FlickLeft Main Right',
    nativeFlickRightMainLeft: 'Our Notes Native FlickRight Main Left',
    nativeFlickRightMainMiddle: 'Our Notes Native FlickRight Main Middle',
    nativeFlickRightMainRight: 'Our Notes Native FlickRight Main Right',
    nativeTraceMainLeft: 'Our Notes Native Trace Main Left',
    nativeTraceMainMiddle: 'Our Notes Native Trace Main Middle',
    nativeTraceMainRight: 'Our Notes Native Trace Main Right',
    nativeNodeMainLeft: 'Our Notes Native Node Main Left',
    nativeNodeMainMiddle: 'Our Notes Native Node Main Middle',
    nativeNodeMainRight: 'Our Notes Native Node Main Right',
} as const

export const getNativeNoteCapId = (sprites: { [Key in keyof typeof nativeNoteCapSprites]: { id: SkinSpriteId } }, kind: number, tilt: number, right: boolean): SkinSpriteId => {
    if (kind === 0) {
        if (tilt === 0) return right ? sprites.nativeTapRight0.id : sprites.nativeTapLeft0.id
        if (tilt === 1) return right ? sprites.nativeTapRight1.id : sprites.nativeTapLeft1.id
        if (tilt === 2) return right ? sprites.nativeTapRight2.id : sprites.nativeTapLeft2.id
        if (tilt === 3) return right ? sprites.nativeTapRight3.id : sprites.nativeTapLeft3.id
        if (tilt === 4) return right ? sprites.nativeTapRight4.id : sprites.nativeTapLeft4.id
        if (tilt === 5) return right ? sprites.nativeTapRight5.id : sprites.nativeTapLeft5.id
        return right ? sprites.nativeTapRight6.id : sprites.nativeTapLeft6.id
    }
    if (kind === 1) {
        if (tilt === 0) return right ? sprites.nativeSlideRight0.id : sprites.nativeSlideLeft0.id
        if (tilt === 1) return right ? sprites.nativeSlideRight1.id : sprites.nativeSlideLeft1.id
        if (tilt === 2) return right ? sprites.nativeSlideRight2.id : sprites.nativeSlideLeft2.id
        if (tilt === 3) return right ? sprites.nativeSlideRight3.id : sprites.nativeSlideLeft3.id
        if (tilt === 4) return right ? sprites.nativeSlideRight4.id : sprites.nativeSlideLeft4.id
        if (tilt === 5) return right ? sprites.nativeSlideRight5.id : sprites.nativeSlideLeft5.id
        return right ? sprites.nativeSlideRight6.id : sprites.nativeSlideLeft6.id
    }
    if (kind === 2) {
        if (tilt === 0) return right ? sprites.nativeEndRight0.id : sprites.nativeEndLeft0.id
        if (tilt === 1) return right ? sprites.nativeEndRight1.id : sprites.nativeEndLeft1.id
        if (tilt === 2) return right ? sprites.nativeEndRight2.id : sprites.nativeEndLeft2.id
        if (tilt === 3) return right ? sprites.nativeEndRight3.id : sprites.nativeEndLeft3.id
        if (tilt === 4) return right ? sprites.nativeEndRight4.id : sprites.nativeEndLeft4.id
        if (tilt === 5) return right ? sprites.nativeEndRight5.id : sprites.nativeEndLeft5.id
        return right ? sprites.nativeEndRight6.id : sprites.nativeEndLeft6.id
    }
    if (kind === 3) {
        if (tilt === 0) return right ? sprites.nativeFlickRight0.id : sprites.nativeFlickLeft0.id
        if (tilt === 1) return right ? sprites.nativeFlickRight1.id : sprites.nativeFlickLeft1.id
        if (tilt === 2) return right ? sprites.nativeFlickRight2.id : sprites.nativeFlickLeft2.id
        if (tilt === 3) return right ? sprites.nativeFlickRight3.id : sprites.nativeFlickLeft3.id
        if (tilt === 4) return right ? sprites.nativeFlickRight4.id : sprites.nativeFlickLeft4.id
        if (tilt === 5) return right ? sprites.nativeFlickRight5.id : sprites.nativeFlickLeft5.id
        return right ? sprites.nativeFlickRight6.id : sprites.nativeFlickLeft6.id
    }
    if (kind === 4) {
        if (tilt === 0) return right ? sprites.nativeFlickLeftRight0.id : sprites.nativeFlickLeftLeft0.id
        if (tilt === 1) return right ? sprites.nativeFlickLeftRight1.id : sprites.nativeFlickLeftLeft1.id
        if (tilt === 2) return right ? sprites.nativeFlickLeftRight2.id : sprites.nativeFlickLeftLeft2.id
        if (tilt === 3) return right ? sprites.nativeFlickLeftRight3.id : sprites.nativeFlickLeftLeft3.id
        if (tilt === 4) return right ? sprites.nativeFlickLeftRight4.id : sprites.nativeFlickLeftLeft4.id
        if (tilt === 5) return right ? sprites.nativeFlickLeftRight5.id : sprites.nativeFlickLeftLeft5.id
        return right ? sprites.nativeFlickLeftRight6.id : sprites.nativeFlickLeftLeft6.id
    }
    if (kind === 5) {
        if (tilt === 0) return right ? sprites.nativeFlickRightRight0.id : sprites.nativeFlickRightLeft0.id
        if (tilt === 1) return right ? sprites.nativeFlickRightRight1.id : sprites.nativeFlickRightLeft1.id
        if (tilt === 2) return right ? sprites.nativeFlickRightRight2.id : sprites.nativeFlickRightLeft2.id
        if (tilt === 3) return right ? sprites.nativeFlickRightRight3.id : sprites.nativeFlickRightLeft3.id
        if (tilt === 4) return right ? sprites.nativeFlickRightRight4.id : sprites.nativeFlickRightLeft4.id
        if (tilt === 5) return right ? sprites.nativeFlickRightRight5.id : sprites.nativeFlickRightLeft5.id
        return right ? sprites.nativeFlickRightRight6.id : sprites.nativeFlickRightLeft6.id
    }
    if (kind === 6) {
        if (tilt === 0) return right ? sprites.nativeTraceRight0.id : sprites.nativeTraceLeft0.id
        if (tilt === 1) return right ? sprites.nativeTraceRight1.id : sprites.nativeTraceLeft1.id
        if (tilt === 2) return right ? sprites.nativeTraceRight2.id : sprites.nativeTraceLeft2.id
        if (tilt === 3) return right ? sprites.nativeTraceRight3.id : sprites.nativeTraceLeft3.id
        if (tilt === 4) return right ? sprites.nativeTraceRight4.id : sprites.nativeTraceLeft4.id
        if (tilt === 5) return right ? sprites.nativeTraceRight5.id : sprites.nativeTraceLeft5.id
        return right ? sprites.nativeTraceRight6.id : sprites.nativeTraceLeft6.id
    }
    {
        if (tilt === 0) return right ? sprites.nativeNodeRight0.id : sprites.nativeNodeLeft0.id
        if (tilt === 1) return right ? sprites.nativeNodeRight1.id : sprites.nativeNodeLeft1.id
        if (tilt === 2) return right ? sprites.nativeNodeRight2.id : sprites.nativeNodeLeft2.id
        if (tilt === 3) return right ? sprites.nativeNodeRight3.id : sprites.nativeNodeLeft3.id
        if (tilt === 4) return right ? sprites.nativeNodeRight4.id : sprites.nativeNodeLeft4.id
        if (tilt === 5) return right ? sprites.nativeNodeRight5.id : sprites.nativeNodeLeft5.id
        return right ? sprites.nativeNodeRight6.id : sprites.nativeNodeLeft6.id
    }
}
const mainId = (sprites: { [Key in keyof typeof nativeNoteCapSprites]: { id: SkinSpriteId } }, kind: number, part: number): SkinSpriteId => {
    if (kind === 0) return part === 0 ? sprites.nativeTapMainLeft.id : part === 1 ? sprites.nativeTapMainMiddle.id : sprites.nativeTapMainRight.id
    if (kind === 1) return part === 0 ? sprites.nativeSlideMainLeft.id : part === 1 ? sprites.nativeSlideMainMiddle.id : sprites.nativeSlideMainRight.id
    if (kind === 2) return part === 0 ? sprites.nativeEndMainLeft.id : part === 1 ? sprites.nativeEndMainMiddle.id : sprites.nativeEndMainRight.id
    if (kind === 3) return part === 0 ? sprites.nativeFlickMainLeft.id : part === 1 ? sprites.nativeFlickMainMiddle.id : sprites.nativeFlickMainRight.id
    if (kind === 4) return part === 0 ? sprites.nativeFlickLeftMainLeft.id : part === 1 ? sprites.nativeFlickLeftMainMiddle.id : sprites.nativeFlickLeftMainRight.id
    if (kind === 5) return part === 0 ? sprites.nativeFlickRightMainLeft.id : part === 1 ? sprites.nativeFlickRightMainMiddle.id : sprites.nativeFlickRightMainRight.id
    if (kind === 6) return part === 0 ? sprites.nativeTraceMainLeft.id : part === 1 ? sprites.nativeTraceMainMiddle.id : sprites.nativeTraceMainRight.id
    return part === 0 ? sprites.nativeNodeMainLeft.id : part === 1 ? sprites.nativeNodeMainMiddle.id : sprites.nativeNodeMainRight.id
}
export const getNativeNoteMainIds = (sprites: { [Key in keyof typeof nativeNoteCapSprites]: { id: SkinSpriteId } }, kind: number) => ({ left: mainId(sprites, kind, 0), middle: mainId(sprites, kind, 1), right: mainId(sprites, kind, 2) })
