// Generated by scripts/generate-native-arrow-data.ts. Do not edit manually.

export const getNativeArrowSpriteIndexSkin001Up = (width: number) => {
    if (width < 5) return 0
    if (width < 12) return 1
    if (width < 18) return 2
    return 3
}
export const getNativeArrowSpriteWidthSkin001Up = (index: number) => {
    switch (index) {
        case 0: return 249
        case 1: return 351
        case 2: return 504
        case 3: return 607
        default: return 0
    }
}
export const getNativeArrowSpriteHeightSkin001Up = (index: number) => {
    switch (index) {
        case 0: return 278
        case 1: return 278
        case 2: return 278
        case 3: return 278
        default: return 0
    }
}
export const getNativeArrowAnimationSkin001Upduration = (time: number) => {
    return 1
}

export const getNativeArrowAnimationSkin001Upx = (time: number) => {
    return 0
}

export const getNativeArrowAnimationSkin001Upy = (time: number) => {
    const t = time - Math.floor(time / 1) * 1
    return t < 0.5 ? (((15.587730407714844 * (t - 0) + -20.884658813476562) * (t - 0) + 9.14539623260498) * (t - 0) + 0.800000011920929) : (((21.56451988220215 * (t - 0.5) + -15.885333061218262) * (t - 0.5) + -0.04846354201436043) * (t - 0.5) + 2.0999999046325684)
}

export const getNativeArrowAnimationSkin001UpscaleX = (time: number) => {
    return 1
}

export const getNativeArrowAnimationSkin001UpscaleY = (time: number) => {
    return 1
}

export const getNativeArrowAnimationSkin001Upalpha = (time: number) => {
    return 1
}

export const getNativeArrowSpriteIndexSkin001Left = (width: number) => {
    if (width < 5) return 0
    if (width < 7) return 1
    if (width < 10) return 2
    if (width < 13) return 3
    if (width < 16) return 4
    if (width < 19) return 5
    if (width < 21) return 6
    return 7
}
export const getNativeArrowSpriteWidthSkin001Left = (index: number) => {
    switch (index) {
        case 0: return 221
        case 1: return 376
        case 2: return 450
        case 3: return 565
        case 4: return 681
        case 5: return 797
        case 6: return 912
        case 7: return 1027
        default: return 0
    }
}
export const getNativeArrowSpriteHeightSkin001Left = (index: number) => {
    switch (index) {
        case 0: return 200
        case 1: return 216
        case 2: return 216
        case 3: return 216
        case 4: return 216
        case 5: return 216
        case 6: return 216
        case 7: return 216
        default: return 0
    }
}
export const getNativeArrowAnimationSkin001Leftduration = (time: number) => {
    return 1
}

export const getNativeArrowAnimationSkin001Leftx = (time: number) => {
    const t = time - Math.floor(time / 1) * 1
    return t < 0.5 ? (((-8.187931060791016 * (t - 0) + 13.30079174041748) * (t - 0) + -7.603413105010986) * (t - 0) + 1) : (((-0.2362813949584961 * (t - 0.5) + 0.6052802801132202) * (t - 0.5) + -0.4435698390007019) * (t - 0.5) + -0.5)
}

export const getNativeArrowAnimationSkin001Lefty = (time: number) => {
    return 1
}

export const getNativeArrowAnimationSkin001LeftscaleX = (time: number) => {
    return 1
}

export const getNativeArrowAnimationSkin001LeftscaleY = (time: number) => {
    return 1
}

export const getNativeArrowAnimationSkin001Leftalpha = (time: number) => {
    const t = time - Math.floor(time / 1) * 1
    return t < 0.1666666716337204 ? 1 : t < 0.75 ? 1 : (((89.5999984741211 * (t - 0.75) + -33.599998474121094) * (t - 0.75)) * (t - 0.75) + 1)
}

export const getNativeArrowSpriteIndexSkin001Right = (width: number) => {
    if (width < 5) return 0
    if (width < 7) return 1
    if (width < 10) return 2
    if (width < 13) return 3
    if (width < 16) return 4
    if (width < 19) return 5
    if (width < 21) return 6
    return 7
}
export const getNativeArrowSpriteWidthSkin001Right = (index: number) => {
    switch (index) {
        case 0: return 221
        case 1: return 376
        case 2: return 450
        case 3: return 566
        case 4: return 681
        case 5: return 797
        case 6: return 912
        case 7: return 1027
        default: return 0
    }
}
export const getNativeArrowSpriteHeightSkin001Right = (index: number) => {
    switch (index) {
        case 0: return 200
        case 1: return 216
        case 2: return 216
        case 3: return 216
        case 4: return 216
        case 5: return 216
        case 6: return 216
        case 7: return 216
        default: return 0
    }
}
export const getNativeArrowAnimationSkin001Rightduration = (time: number) => {
    return 1
}

export const getNativeArrowAnimationSkin001Rightx = (time: number) => {
    const t = time - Math.floor(time / 1) * 1
    return t < 0.5 ? (((7.383794784545898 * (t - 0) + -11.93160343170166) * (t - 0) + 7.1198530197143555) * (t - 0) + -0.8999999761581421) : (((1.373206377029419 * (t - 0.5) + -1.7387948036193848) * (t - 0.5) + 0.7260957360267639) * (t - 0.5) + 0.6000000238418579)
}

export const getNativeArrowAnimationSkin001Righty = (time: number) => {
    return 1
}

export const getNativeArrowAnimationSkin001RightscaleX = (time: number) => {
    return 1
}

export const getNativeArrowAnimationSkin001RightscaleY = (time: number) => {
    return 1
}

export const getNativeArrowAnimationSkin001Rightalpha = (time: number) => {
    const t = time - Math.floor(time / 1) * 1
    return t < 0.699999988079071 ? (((0.2459019273519516 * (t - 0) + -1.0186764001846313) * (t - 0) + 0.592581570148468) * (t - 0) + 1) : (((48.217098236083984 * (t - 0.699999988079071) + -20.66927719116211) * (t - 0.699999988079071) + -0.47208961844444275) * (t - 0.699999988079071) + 1)
}

export const getNativeArrowSpriteIndexSkin002Up = (width: number) => {
    if (width < 5) return 0
    if (width < 12) return 1
    if (width < 18) return 2
    return 3
}
export const getNativeArrowSpriteWidthSkin002Up = (index: number) => {
    switch (index) {
        case 0: return 229
        case 1: return 391
        case 2: return 504
        case 3: return 647
        default: return 0
    }
}
export const getNativeArrowSpriteHeightSkin002Up = (index: number) => {
    switch (index) {
        case 0: return 205
        case 1: return 249
        case 2: return 291
        case 3: return 328
        default: return 0
    }
}
export const getNativeArrowAnimationSkin002Upduration = (time: number) => {
    return 0.5
}

export const getNativeArrowAnimationSkin002Upx = (time: number) => {
    return 0
}

export const getNativeArrowAnimationSkin002Upy = (time: number) => {
    const t = time - Math.floor(time / 0.5) * 0.5
    return (2.5999999046325684 * (t - 0) + 0.800000011920929)
}

export const getNativeArrowAnimationSkin002UpscaleX = (time: number) => {
    return 0.800000011920929
}

export const getNativeArrowAnimationSkin002UpscaleY = (time: number) => {
    return 0.800000011920929
}

export const getNativeArrowAnimationSkin002Upalpha = (time: number) => {
    return 1
}

export const getNativeArrowSpriteIndexSkin002Left = (width: number) => {
    if (width < 5) return 0
    if (width < 7) return 1
    if (width < 10) return 2
    if (width < 13) return 3
    if (width < 16) return 4
    if (width < 19) return 5
    if (width < 21) return 6
    return 7
}
export const getNativeArrowSpriteWidthSkin002Left = (index: number) => {
    switch (index) {
        case 0: return 191
        case 1: return 315
        case 2: return 439
        case 3: return 563
        case 4: return 687
        case 5: return 811
        case 6: return 935
        case 7: return 1059
        default: return 0
    }
}
export const getNativeArrowSpriteHeightSkin002Left = (index: number) => {
    switch (index) {
        case 0: return 244
        case 1: return 244
        case 2: return 244
        case 3: return 244
        case 4: return 244
        case 5: return 244
        case 6: return 244
        case 7: return 244
        default: return 0
    }
}
export const getNativeArrowAnimationSkin002Leftduration = (time: number) => {
    return 0.5
}

export const getNativeArrowAnimationSkin002Leftx = (time: number) => {
    const t = time - Math.floor(time / 0.5) * 0.5
    return (-3 * (t - 0))
}

export const getNativeArrowAnimationSkin002Lefty = (time: number) => {
    return 0.8500000238418579
}

export const getNativeArrowAnimationSkin002LeftscaleX = (time: number) => {
    return 0.800000011920929
}

export const getNativeArrowAnimationSkin002LeftscaleY = (time: number) => {
    return 0.800000011920929
}

export const getNativeArrowAnimationSkin002Leftalpha = (time: number) => {
    return 1
}

export const getNativeArrowSpriteIndexSkin002Right = (width: number) => {
    if (width < 5) return 0
    if (width < 7) return 1
    if (width < 10) return 2
    if (width < 13) return 3
    if (width < 16) return 4
    if (width < 19) return 5
    if (width < 21) return 6
    return 7
}
export const getNativeArrowSpriteWidthSkin002Right = (index: number) => {
    switch (index) {
        case 0: return 191
        case 1: return 315
        case 2: return 439
        case 3: return 687
        case 4: return 687
        case 5: return 811
        case 6: return 935
        case 7: return 1059
        default: return 0
    }
}
export const getNativeArrowSpriteHeightSkin002Right = (index: number) => {
    switch (index) {
        case 0: return 244
        case 1: return 244
        case 2: return 244
        case 3: return 244
        case 4: return 244
        case 5: return 244
        case 6: return 244
        case 7: return 244
        default: return 0
    }
}
export const getNativeArrowAnimationSkin002Rightduration = (time: number) => {
    return 0.5
}

export const getNativeArrowAnimationSkin002Rightx = (time: number) => {
    const t = time - Math.floor(time / 0.5) * 0.5
    return (3 * (t - 0))
}

export const getNativeArrowAnimationSkin002Righty = (time: number) => {
    return 0.8500000238418579
}

export const getNativeArrowAnimationSkin002RightscaleX = (time: number) => {
    return 0.800000011920929
}

export const getNativeArrowAnimationSkin002RightscaleY = (time: number) => {
    return 0.800000011920929
}

export const getNativeArrowAnimationSkin002Rightalpha = (time: number) => {
    return 1
}

export const getNativeArrowSpriteIndexSkin003Up = (width: number) => {
    if (width < 5) return 0
    if (width < 7) return 1
    if (width < 10) return 2
    if (width < 13) return 3
    if (width < 16) return 4
    if (width < 19) return 5
    if (width < 21) return 6
    return 7
}
export const getNativeArrowSpriteWidthSkin003Up = (index: number) => {
    switch (index) {
        case 0: return 199
        case 1: return 319
        case 2: return 439
        case 3: return 559
        case 4: return 679
        case 5: return 799
        case 6: return 919
        case 7: return 1039
        default: return 0
    }
}
export const getNativeArrowSpriteHeightSkin003Up = (index: number) => {
    switch (index) {
        case 0: return 132
        case 1: return 132
        case 2: return 132
        case 3: return 132
        case 4: return 132
        case 5: return 132
        case 6: return 132
        case 7: return 132
        default: return 0
    }
}
export const getNativeArrowAnimationSkin003Upduration = (time: number) => {
    return 1
}

export const getNativeArrowAnimationSkin003Upx = (time: number) => {
    return 0
}

export const getNativeArrowAnimationSkin003Upy = (time: number) => {
    return 0.6499999761581421
}

export const getNativeArrowAnimationSkin003UpscaleX = (time: number) => {
    return 1.375
}

export const getNativeArrowAnimationSkin003UpscaleY = (time: number) => {
    return 1.375
}

export const getNativeArrowAnimationSkin003Upalpha = (time: number) => {
    return 1
}

export const getNativeArrowSpriteIndexSkin003Left = (width: number) => {
    if (width < 5) return 0
    if (width < 7) return 1
    if (width < 10) return 2
    if (width < 13) return 3
    if (width < 16) return 4
    if (width < 19) return 5
    if (width < 21) return 6
    return 7
}
export const getNativeArrowSpriteWidthSkin003Left = (index: number) => {
    switch (index) {
        case 0: return 261
        case 1: return 356
        case 2: return 455
        case 3: return 586
        case 4: return 739
        case 5: return 760
        case 6: return 780
        case 7: return 1255
        default: return 0
    }
}
export const getNativeArrowSpriteHeightSkin003Left = (index: number) => {
    switch (index) {
        case 0: return 132
        case 1: return 132
        case 2: return 132
        case 3: return 132
        case 4: return 132
        case 5: return 132
        case 6: return 132
        case 7: return 132
        default: return 0
    }
}
export const getNativeArrowAnimationSkin003Leftduration = (time: number) => {
    return 1
}

export const getNativeArrowAnimationSkin003Leftx = (time: number) => {
    return -1.0800000429153442
}

export const getNativeArrowAnimationSkin003Lefty = (time: number) => {
    return 1.0399999618530273
}

export const getNativeArrowAnimationSkin003LeftscaleX = (time: number) => {
    return 1.2999999523162842
}

export const getNativeArrowAnimationSkin003LeftscaleY = (time: number) => {
    return 1.2999999523162842
}

export const getNativeArrowAnimationSkin003Leftalpha = (time: number) => {
    return 1
}

export const getNativeArrowSpriteIndexSkin003Right = (width: number) => {
    if (width < 5) return 0
    if (width < 7) return 1
    if (width < 10) return 2
    if (width < 13) return 3
    if (width < 16) return 4
    if (width < 19) return 5
    if (width < 21) return 6
    return 7
}
export const getNativeArrowSpriteWidthSkin003Right = (index: number) => {
    switch (index) {
        case 0: return 261
        case 1: return 356
        case 2: return 455
        case 3: return 586
        case 4: return 739
        case 5: return 760
        case 6: return 780
        case 7: return 1255
        default: return 0
    }
}
export const getNativeArrowSpriteHeightSkin003Right = (index: number) => {
    switch (index) {
        case 0: return 132
        case 1: return 132
        case 2: return 132
        case 3: return 132
        case 4: return 132
        case 5: return 132
        case 6: return 132
        case 7: return 132
        default: return 0
    }
}
export const getNativeArrowAnimationSkin003Rightduration = (time: number) => {
    return 1
}

export const getNativeArrowAnimationSkin003Rightx = (time: number) => {
    return 1.0800000429153442
}

export const getNativeArrowAnimationSkin003Righty = (time: number) => {
    return 1.0399999618530273
}

export const getNativeArrowAnimationSkin003RightscaleX = (time: number) => {
    return 1.2999999523162842
}

export const getNativeArrowAnimationSkin003RightscaleY = (time: number) => {
    return 1.2999999523162842
}

export const getNativeArrowAnimationSkin003Rightalpha = (time: number) => {
    return 1
}

