// Generated by scripts/generate-native-note-geometry.ts.

const mainmainH = (skin002: boolean, skin003: boolean, kind: number) => {
    if (skin002) {
        return 0.05176470588235294
    }
    if (skin003) {
        if (kind === 6) return 0.04823529411764706
        if (kind === 7) return 0.04647058823529412
        if (kind === 0 || kind === 1) return 0.06705882352941177
        return 0.06
    }
    {
        if (kind === 6) return 0.03470588235294118
        if (kind === 7) return 0.025294117647058825
        return 0.04823529411764706
    }
}

const mainmarkW = (skin002: boolean, skin003: boolean, kind: number) => {
    if (skin002) {
        if (kind === 6) return 0.4140845070422535
        if (kind === 2 || kind === 7) return 0.3126760563380282
        return 0.2619718309859155
    }
    if (skin003) {
        if (kind === 0) return 0.28732394366197184
        if (kind === 6) return 0.2535211267605634
        if (kind === 2 || kind === 7) return 0.4140845070422535
        return 0.3126760563380282
    }
    {
        if (kind === 0) return 0.21971830985915494
        if (kind === 6) return 0.5492957746478874
        if (kind === 2 || kind === 7) return 0.5830985915492958
        return 0.22816901408450704
    }
}

const mainmarkH = (skin002: boolean, skin003: boolean, kind: number) => {
    if (skin002) {
        if (kind === 6) return 0.028823529411764706
        if (kind === 2 || kind === 7) return 0.02176470588235294
        return 0.018235294117647058
    }
    if (skin003) {
        if (kind === 0) return 0.019411764705882354
        if (kind === 6) return 0.01764705882352941
        if (kind === 2 || kind === 7) return 0.028823529411764706
        return 0.02176470588235294
    }
    {
        if (kind === 0) return 0.015294117647058824
        if (kind === 6) return 0.03823529411764706
        if (kind === 2 || kind === 7) return 0.04058823529411765
        return 0.01588235294117647
    }
}

const mainmarkX = (skin002: boolean, skin003: boolean, kind: number) => {
    return 0
}

const mainmarkY = (skin002: boolean, skin003: boolean, kind: number) => {
    return 0
}

const mainborderLeft = (skin002: boolean, skin003: boolean, kind: number) => {
    return 0.03380281690140845
}

const mainborderRight = (skin002: boolean, skin003: boolean, kind: number) => {
    return 0.03380281690140845
}

const partw = (skin002: boolean, skin003: boolean, kind: number, tilt: number, right: boolean) => {
    const key = tilt * 2 + (right ? 1 : 0)
    if (skin002) {
        if (kind === 0) {
            if (key === 2) return 0.6338028169014085
            if (key === 4) return 0.6591549295774648
            if (key === 5) return 0.6929577464788732
            if (key === 6) return 0.6845070422535211
            if (key === 7) return 0.6676056338028169
            if (key === 11) return 0.7436619718309859
            if (key === 12) return 0
            if (key === 13) return 0.7690140845070422
            if (key === 0 || key === 1) return 0.6
            if (key === 3 || key === 9) return 0.7267605633802817
            return 0.7098591549295775
        }
        if (kind === 1) {
            if (key === 0) return 0.5915492957746479
            if (key === 1) return 0.6
            if (key === 2) return 0.6338028169014085
            if (key === 11) return 0.7436619718309859
            if (key === 12) return 0
            if (key === 13) return 0.7690140845070422
            if (key === 3 || key === 9) return 0.7183098591549296
            if (key === 4 || key === 7) return 0.6676056338028169
            if (key === 5 || key === 6) return 0.676056338028169
            return 0.7098591549295775
        }
        if (kind === 2) {
            if (key === 0) return 0.5746478873239437
            if (key === 3) return 0.6929577464788732
            if (key === 4) return 0.6338028169014085
            if (key === 5) return 0.6084507042253521
            if (key === 6) return 0.6422535211267606
            if (key === 7) return 0.6253521126760564
            if (key === 8) return 0.7098591549295775
            if (key === 9) return 0.676056338028169
            if (key === 12) return 0
            if (key === 13) return 0.7690140845070422
            if (key === 1 || key === 2) return 0.6
            return 0.7436619718309859
        }
        if (kind === 3) {
            if (key === 0) return 0.5492957746478874
            if (key === 1) return 0.5408450704225352
            if (key === 2) return 0.5577464788732395
            if (key === 3) return 0.5661971830985916
            if (key === 4) return 0.5915492957746479
            if (key === 5) return 0.6
            if (key === 6) return 0.6253521126760564
            if (key === 7) return 0.6169014084507042
            if (key === 8) return 0.6591549295774648
            if (key === 9) return 0.6507042253521127
            if (key === 12) return 0
            if (key === 13) return 0.6676056338028169
            return 0.7014084507042253
        }
        if (kind === 4) {
            if (key === 0) return 0.5408450704225352
            if (key === 1) return 0.532394366197183
            if (key === 2) return 0.5577464788732395
            if (key === 3) return 0.5492957746478874
            if (key === 6) return 0.6253521126760564
            if (key === 7) return 0.6169014084507042
            if (key === 10) return 0.7014084507042253
            if (key === 11) return 0.6929577464788732
            if (key === 12) return 0
            if (key === 13) return 0.676056338028169
            if (key === 4 || key === 5) return 0.5915492957746479
            return 0.6591549295774648
        }
        if (kind === 5) {
            if (key === 0) return 0.532394366197183
            if (key === 1) return 0.523943661971831
            if (key === 2) return 0.5577464788732395
            if (key === 3) return 0.5492957746478874
            if (key === 4) return 0.5915492957746479
            if (key === 5) return 0.5830985915492958
            if (key === 9) return 0.6507042253521127
            if (key === 10) return 0.7098591549295775
            if (key === 11) return 0.7014084507042253
            if (key === 12) return 0
            if (key === 6 || key === 7) return 0.6169014084507042
            return 0.6676056338028169
        }
        if (kind === 6) {
            if (key === 1) return 0.29577464788732394
            if (key === 8) return 0.3380281690140845
            if (key === 9) return 0.38028169014084506
            if (key === 11) return 0.37183098591549296
            if (key === 12) return 0
            if (key === 13) return 0.447887323943662
            if (key === 0 || key === 3) return 0.3126760563380282
            if (key === 2 || key === 4) return 0.30422535211267604
            if (key === 5 || key === 6) return 0.3295774647887324
            return 0.36338028169014086
        }
        {
            if (key === 0) return 0.17746478873239438
            if (key === 2) return 0.18591549295774648
            if (key === 5) return 0.19436619718309858
            if (key === 7) return 0.21971830985915494
            if (key === 9) return 0.2112676056338028
            if (key === 12) return 0
            if (key === 13) return 0.2704225352112676
            if (key === 6 || key === 11) return 0.23661971830985915
            if (key === 8 || key === 10) return 0.22816901408450704
            return 0.2028169014084507
        }
    }
    if (skin003) {
        if (kind === 0) {
            if (key === 2) return 0.4647887323943662
            if (key === 3) return 0.4394366197183099
            if (key === 4) return 0.5070422535211268
            if (key === 5) return 0.4732394366197183
            if (key === 7) return 0.49859154929577465
            if (key === 12) return 0
            if (key === 13) return 0.6253521126760564
            if (key === 0 || key === 1) return 0.4225352112676056
            if (key === 10 || key === 11) return 0.6
            return 0.5915492957746479
        }
        if (kind === 1) {
            if (key === 2) return 0.4647887323943662
            if (key === 3) return 0.4394366197183099
            if (key === 4) return 0.5070422535211268
            if (key === 5) return 0.4732394366197183
            if (key === 7) return 0.49859154929577465
            if (key === 10) return 0.6591549295774648
            if (key === 11) return 0.6
            if (key === 12) return 0
            if (key === 13) return 0.6253521126760564
            if (key === 0 || key === 1) return 0.4225352112676056
            return 0.5915492957746479
        }
        if (kind === 2) {
            if (key === 2) return 0.4647887323943662
            if (key === 3) return 0.4394366197183099
            if (key === 4) return 0.5070422535211268
            if (key === 5) return 0.4732394366197183
            if (key === 7) return 0.49859154929577465
            if (key === 10) return 0.6591549295774648
            if (key === 11) return 0.6
            if (key === 12) return 0
            if (key === 13) return 0.6253521126760564
            if (key === 0 || key === 1) return 0.4225352112676056
            return 0.5915492957746479
        }
        if (kind === 3) {
            if (key === 2) return 0.4647887323943662
            if (key === 3) return 0.4394366197183099
            if (key === 4) return 0.5070422535211268
            if (key === 5) return 0.4732394366197183
            if (key === 7) return 0.49859154929577465
            if (key === 10) return 0.6591549295774648
            if (key === 11) return 0.6
            if (key === 12) return 0
            if (key === 13) return 0.6253521126760564
            if (key === 0 || key === 1) return 0.4225352112676056
            return 0.5915492957746479
        }
        if (kind === 4) {
            if (key === 2) return 0.4647887323943662
            if (key === 3) return 0.4394366197183099
            if (key === 4) return 0.5070422535211268
            if (key === 5) return 0.4732394366197183
            if (key === 7) return 0.49859154929577465
            if (key === 10) return 0.6591549295774648
            if (key === 11) return 0.6
            if (key === 12) return 0
            if (key === 13) return 0.6253521126760564
            if (key === 0 || key === 1) return 0.4225352112676056
            return 0.5915492957746479
        }
        if (kind === 5) {
            if (key === 2) return 0.4647887323943662
            if (key === 3) return 0.4394366197183099
            if (key === 4) return 0.5070422535211268
            if (key === 5) return 0.4732394366197183
            if (key === 7) return 0.49859154929577465
            if (key === 10) return 0.6591549295774648
            if (key === 11) return 0.6
            if (key === 12) return 0
            if (key === 13) return 0.6253521126760564
            if (key === 0 || key === 1) return 0.4225352112676056
            return 0.5915492957746479
        }
        if (kind === 6) {
            if (key === 0) return 0.3971830985915493
            if (key === 1) return 0.38873239436619716
            if (key === 2) return 0.4056338028169014
            if (key === 3) return 0.4140845070422535
            if (key === 4) return 0.4394366197183099
            if (key === 5) return 0.4309859154929577
            if (key === 9) return 0.4732394366197183
            if (key === 10) return 0.532394366197183
            if (key === 12) return 0
            if (key === 6 || key === 7) return 0.48169014084507045
            return 0.5492957746478874
        }
        {
            if (key === 9) return 0.3971830985915493
            if (key === 11) return 0.4140845070422535
            if (key === 12) return 0
            if (key === 0 || key === 2) return 0.30422535211267604
            if (key === 10 || key === 13) return 0.4056338028169014
            if (key === 4 || key === 6 || key === 8) return 0.35492957746478876
            return 0.36338028169014086
        }
    }
    {
        if (kind === 0) {
            if (key === 7) return 0.447887323943662
            if (key === 8) return 0.6507042253521127
            if (key === 9) return 0.5661971830985916
            if (key === 10) return 0.6845070422535211
            if (key === 11) return 0.5408450704225352
            if (key === 12) return 0
            if (key === 13) return 0.6253521126760564
            if (key === 0 || key === 1) return 0.30422535211267604
            if (key === 3 || key === 5) return 0.36338028169014086
            return 0.5492957746478874
        }
        if (kind === 1) {
            if (key === 7) return 0.447887323943662
            if (key === 8) return 0.6507042253521127
            if (key === 9) return 0.5661971830985916
            if (key === 10) return 0.6845070422535211
            if (key === 11) return 0.5408450704225352
            if (key === 12) return 0
            if (key === 13) return 0.6253521126760564
            if (key === 0 || key === 1) return 0.30422535211267604
            if (key === 3 || key === 5) return 0.36338028169014086
            return 0.5492957746478874
        }
        if (kind === 2) {
            if (key === 2) return 0.49859154929577465
            if (key === 3) return 0.4563380281690141
            if (key === 4) return 0.49014084507042255
            if (key === 5) return 0.48169014084507045
            if (key === 7) return 0.5408450704225352
            if (key === 10) return 0.6591549295774648
            if (key === 11) return 0.7183098591549296
            if (key === 12) return 0
            if (key === 13) return 0.8028169014084507
            if (key === 0 || key === 1) return 0.30422535211267604
            return 0.6507042253521127
        }
        if (kind === 3) {
            if (key === 7) return 0.447887323943662
            if (key === 8) return 0.6507042253521127
            if (key === 9) return 0.5661971830985916
            if (key === 10) return 0.6845070422535211
            if (key === 11) return 0.5408450704225352
            if (key === 12) return 0
            if (key === 13) return 0.6253521126760564
            if (key === 0 || key === 1) return 0.30422535211267604
            if (key === 3 || key === 5) return 0.36338028169014086
            return 0.5492957746478874
        }
        if (kind === 4) {
            if (key === 7) return 0.447887323943662
            if (key === 8) return 0.6507042253521127
            if (key === 9) return 0.5661971830985916
            if (key === 10) return 0.6845070422535211
            if (key === 11) return 0.5408450704225352
            if (key === 12) return 0
            if (key === 13) return 0.6253521126760564
            if (key === 0 || key === 1) return 0.30422535211267604
            if (key === 3 || key === 5) return 0.36338028169014086
            return 0.5492957746478874
        }
        if (kind === 5) {
            if (key === 7) return 0.447887323943662
            if (key === 8) return 0.6507042253521127
            if (key === 9) return 0.5661971830985916
            if (key === 10) return 0.6845070422535211
            if (key === 11) return 0.5408450704225352
            if (key === 12) return 0
            if (key === 13) return 0.6253521126760564
            if (key === 0 || key === 1) return 0.30422535211267604
            if (key === 3 || key === 5) return 0.36338028169014086
            return 0.5492957746478874
        }
        if (kind === 6) {
            if (key === 6) return 0.3380281690140845
            if (key === 8) return 0.36338028169014086
            if (key === 9) return 0.37183098591549296
            if (key === 10) return 0.4563380281690141
            if (key === 11) return 0.38028169014084506
            if (key === 12) return 0
            if (key === 13) return 0.4394366197183099
            if (key === 0 || key === 1) return 0.2535211267605634
            if (key === 3 || key === 7) return 0.3211267605633803
            return 0.29577464788732394
        }
        {
            if (key === 3) return 0.27887323943661974
            if (key === 7) return 0.30422535211267604
            if (key === 10) return 0.3126760563380282
            if (key === 11) return 0.35492957746478876
            if (key === 12) return 0
            if (key === 13) return 0.3464788732394366
            if (key === 0 || key === 1) return 0.19436619718309858
            if (key === 2 || key === 5) return 0.21971830985915494
            if (key === 4 || key === 9) return 0.23661971830985915
            return 0.2619718309859155
        }
    }
}

const parth = (skin002: boolean, skin003: boolean, kind: number, tilt: number, right: boolean) => {
    const key = tilt * 2 + (right ? 1 : 0)
    if (skin002) {
        if (kind === 0) {
            if (key === 3) return 0.05235294117647059
            if (key === 12) return 0
            return 0.05176470588235294
        }
        if (kind === 1) {
            if (key === 3) return 0.05235294117647059
            if (key === 12) return 0
            return 0.05176470588235294
        }
        if (kind === 2) {
            if (key === 12) return 0
            return 0.05176470588235294
        }
        if (kind === 3) {
            if (key === 12) return 0
            return 0.05176470588235294
        }
        if (kind === 4) {
            if (key === 12) return 0
            return 0.05176470588235294
        }
        if (kind === 5) {
            if (key === 12) return 0
            return 0.05176470588235294
        }
        if (kind === 6) {
            if (key === 12) return 0
            return 0.05176470588235294
        }
        {
            if (key === 12) return 0
            return 0.05176470588235294
        }
    }
    if (skin003) {
        if (kind === 0) {
            if (key === 12) return 0
            return 0.06705882352941177
        }
        if (kind === 1) {
            if (key === 12) return 0
            return 0.06705882352941177
        }
        if (kind === 2) {
            if (key === 12) return 0
            return 0.06
        }
        if (kind === 3) {
            if (key === 12) return 0
            return 0.06
        }
        if (kind === 4) {
            if (key === 12) return 0
            return 0.06
        }
        if (kind === 5) {
            if (key === 12) return 0
            return 0.06
        }
        if (kind === 6) {
            if (key === 12) return 0
            return 0.04823529411764706
        }
        {
            if (key === 12) return 0
            return 0.04647058823529412
        }
    }
    {
        if (kind === 0) {
            if (key === 12) return 0
            return 0.04823529411764706
        }
        if (kind === 1) {
            if (key === 12) return 0
            return 0.04823529411764706
        }
        if (kind === 2) {
            if (key === 12) return 0
            return 0.04823529411764706
        }
        if (kind === 3) {
            if (key === 12) return 0
            return 0.04823529411764706
        }
        if (kind === 4) {
            if (key === 12) return 0
            return 0.04823529411764706
        }
        if (kind === 5) {
            if (key === 12) return 0
            return 0.04823529411764706
        }
        if (kind === 6) {
            if (key === 12) return 0
            return 0.03470588235294118
        }
        {
            if (key === 12) return 0
            return 0.025294117647058825
        }
    }
}

const partx = (skin002: boolean, skin003: boolean, kind: number, tilt: number, right: boolean) => {
    return 0
}

const party = (skin002: boolean, skin003: boolean, kind: number, tilt: number, right: boolean) => {
    return 0
}

const parttightW = (skin002: boolean, skin003: boolean, kind: number, tilt: number, right: boolean) => {
    const key = tilt * 2 + (right ? 1 : 0)
    if (skin002) {
        if (kind === 0) {
            if (key === 2) return 0.6338028169014085
            if (key === 4) return 0.6591549295774648
            if (key === 5) return 0.6842809972628742
            if (key === 6) return 0.6845070422535211
            if (key === 7) return 0.6676056338028169
            if (key === 11) return 0.7436619718309859
            if (key === 12) return 0
            if (key === 13) return 0.7690140845070422
            if (key === 0 || key === 1) return 0.6
            if (key === 3 || key === 9) return 0.7267605633802817
            return 0.7098591549295775
        }
        if (kind === 1) {
            if (key === 0) return 0.5915492957746479
            if (key === 1) return 0.6
            if (key === 2) return 0.6338028169014085
            if (key === 11) return 0.7436619718309859
            if (key === 12) return 0
            if (key === 13) return 0.7690140845070422
            if (key === 3 || key === 9) return 0.7183098591549296
            if (key === 4 || key === 7) return 0.6676056338028169
            if (key === 5 || key === 6) return 0.676056338028169
            return 0.7098591549295775
        }
        if (kind === 2) {
            if (key === 0) return 0.4556947734993948
            if (key === 1) return 0.4641454454878686
            if (key === 2) return 0.5068162085304797
            if (key === 3) return 0.5824553368796765
            if (key === 4) return 0.5571032242036201
            if (key === 5) return 0.5490697296572403
            if (key === 6) return 0.5740046326543243
            if (key === 7) return 0.5402017835160376
            if (key === 8) return 0.6332872202698614
            if (key === 9) return 0.6251260676854093
            if (key === 10) return 0.624708858006437
            if (key === 11) return 0.6759472484319983
            if (key === 12) return 0
            return 0.6842809972628742
        }
        if (kind === 3) {
            if (key === 0) return 0.5492957746478874
            if (key === 1) return 0.5408450704225352
            if (key === 2) return 0.5577464788732395
            if (key === 3) return 0.5661971830985916
            if (key === 4) return 0.5915492957746479
            if (key === 5) return 0.6
            if (key === 6) return 0.6253521126760564
            if (key === 7) return 0.6169014084507042
            if (key === 8) return 0.6591549295774648
            if (key === 9) return 0.6507042253521127
            if (key === 12) return 0
            if (key === 13) return 0.6676056338028169
            return 0.7014084507042253
        }
        if (kind === 4) {
            if (key === 0) return 0.5408450704225352
            if (key === 1) return 0.532394366197183
            if (key === 2) return 0.5577464788732395
            if (key === 3) return 0.5492957746478874
            if (key === 6) return 0.6253521126760564
            if (key === 7) return 0.6169014084507042
            if (key === 10) return 0.7014084507042253
            if (key === 11) return 0.6929577464788732
            if (key === 12) return 0
            if (key === 13) return 0.676056338028169
            if (key === 4 || key === 5) return 0.5915492957746479
            return 0.6591549295774648
        }
        if (kind === 5) {
            if (key === 0) return 0.532394366197183
            if (key === 1) return 0.523943661971831
            if (key === 2) return 0.5577464788732395
            if (key === 3) return 0.5492957746478874
            if (key === 4) return 0.5915492957746479
            if (key === 5) return 0.5830985915492958
            if (key === 9) return 0.6507042253521127
            if (key === 10) return 0.7098591549295775
            if (key === 11) return 0.7014084507042253
            if (key === 12) return 0
            if (key === 6 || key === 7) return 0.6169014084507042
            return 0.6676056338028169
        }
        if (kind === 6) {
            if (key === 0) return 0.29513139321770465
            if (key === 1) return 0.2951313609808264
            if (key === 3) return 0.3126760563380282
            if (key === 5) return 0.3295774647887324
            if (key === 6) return 0.32893417788223483
            if (key === 8) return 0.3380281690140845
            if (key === 9) return 0.37160490868796764
            if (key === 11) return 0.3711876990089954
            if (key === 12) return 0
            if (key === 13) return 0.447887323943662
            if (key === 2 || key === 4) return 0.3035820652061785
            return 0.36338028169014086
        }
        {
            if (key === 0) return 0.17746478873239438
            if (key === 2) return 0.18591549295774648
            if (key === 5) return 0.19436619718309858
            if (key === 7) return 0.21971830985915494
            if (key === 9) return 0.2112676056338028
            if (key === 12) return 0
            if (key === 13) return 0.2704225352112676
            if (key === 6 || key === 11) return 0.23661971830985915
            if (key === 8 || key === 10) return 0.22816901408450704
            return 0.2028169014084507
        }
    }
    if (skin003) {
        if (kind === 0) {
            if (key === 2) return 0.4647887323943662
            if (key === 3) return 0.4394366197183099
            if (key === 4) return 0.5070422535211268
            if (key === 5) return 0.4732394366197183
            if (key === 7) return 0.49859154929577465
            if (key === 9) return 0.5909060411050286
            if (key === 10) return 0.6
            if (key === 11) return 0.5993567453303807
            if (key === 12) return 0
            if (key === 13) return 0.6253521126760564
            if (key === 0 || key === 1) return 0.4225352112676056
            return 0.5915492957746479
        }
        if (kind === 1) {
            if (key === 2) return 0.4647887323943662
            if (key === 3) return 0.4394366197183099
            if (key === 4) return 0.5070422535211268
            if (key === 5) return 0.4732394366197183
            if (key === 7) return 0.49859154929577465
            if (key === 9) return 0.5909060411050286
            if (key === 10) return 0.6416102664571413
            if (key === 11) return 0.5993567453303807
            if (key === 12) return 0
            if (key === 13) return 0.6253521126760564
            if (key === 0 || key === 1) return 0.4225352112676056
            return 0.5915492957746479
        }
        if (kind === 2) {
            if (key === 2) return 0.4472440692740427
            if (key === 3) return 0.4389318869147502
            if (key === 4) return 0.4979482623892771
            if (key === 5) return 0.4641454454878686
            if (key === 7) return 0.4898342078840229
            if (key === 9) return 0.5489891374614877
            if (key === 10) return 0.6167923188545335
            if (key === 11) return 0.5576373892770686
            if (key === 12) return 0
            if (key === 13) return 0.6084507042253521
            if (key === 0 || key === 1) return 0.4054077255893761
            return 0.5915492957746479
        }
        if (kind === 3) {
            if (key === 2) return 0.4647887323943662
            if (key === 3) return 0.4394366197183099
            if (key === 4) return 0.5070422535211268
            if (key === 5) return 0.4732394366197183
            if (key === 7) return 0.49859154929577465
            if (key === 9) return 0.5909060411050286
            if (key === 10) return 0.6416102664571413
            if (key === 11) return 0.5993567453303807
            if (key === 12) return 0
            if (key === 13) return 0.6253521126760564
            if (key === 0 || key === 1) return 0.4225352112676056
            return 0.5915492957746479
        }
        if (kind === 4) {
            if (key === 2) return 0.4647887323943662
            if (key === 3) return 0.4394366197183099
            if (key === 4) return 0.5070422535211268
            if (key === 5) return 0.4732394366197183
            if (key === 7) return 0.49859154929577465
            if (key === 9) return 0.5909060411050286
            if (key === 10) return 0.6416102664571413
            if (key === 11) return 0.5993567453303807
            if (key === 12) return 0
            if (key === 13) return 0.6253521126760564
            if (key === 0 || key === 1) return 0.4225352112676056
            return 0.5915492957746479
        }
        if (kind === 5) {
            if (key === 2) return 0.4647887323943662
            if (key === 3) return 0.4394366197183099
            if (key === 4) return 0.5070422535211268
            if (key === 5) return 0.4732394366197183
            if (key === 7) return 0.49859154929577465
            if (key === 9) return 0.5909060411050286
            if (key === 10) return 0.6416102664571413
            if (key === 11) return 0.5993567453303807
            if (key === 12) return 0
            if (key === 13) return 0.6253521126760564
            if (key === 0 || key === 1) return 0.4225352112676056
            return 0.5915492957746479
        }
        if (kind === 6) {
            if (key === 0) return 0.3965398116850517
            if (key === 1) return 0.38873239436619716
            if (key === 2) return 0.4056338028169014
            if (key === 3) return 0.4140845070422535
            if (key === 4) return 0.4394366197183099
            if (key === 5) return 0.4309859154929577
            if (key === 9) return 0.4732394366197183
            if (key === 10) return 0.532394366197183
            if (key === 12) return 0
            if (key === 6 || key === 7) return 0.48169014084507045
            return 0.5492957746478874
        }
        {
            if (key === 0) return 0.2786471622090944
            if (key === 1) return 0.320900683335855
            if (key === 2) return 0.2870978664344465
            if (key === 3) return 0.3293513875612071
            if (key === 4) return 0.3292708276023327
            if (key === 5) return 0.34625279601191133
            if (key === 6) return 0.3289342101191131
            if (key === 7) return 0.36315420446261554
            if (key === 8) return 0.3544959269778829
            if (key === 9) return 0.3885063171386719
            if (key === 10) return 0.4049905159104038
            if (key === 11) return 0.4138584298147282
            if (key === 12) return 0
            return 0.4056338028169014
        }
    }
    {
        if (kind === 0) {
            if (key === 0) return 0.28668068899235255
            if (key === 2) return 0.40499054814728214
            if (key === 4) return 0.4795747568909551
            if (key === 5) return 0.2951313609808264
            if (key === 6) return 0.548933174240757
            if (key === 7) return 0.3714683855083627
            if (key === 8) return 0.5913232507840008
            if (key === 9) return 0.4899147678428972
            if (key === 10) return 0.6845070422535211
            if (key === 11) return 0.4979482623892771
            if (key === 12) return 0
            if (key === 13) return 0.5571854927170444
            return 0.2866806567554743
        }
        if (kind === 1) {
            if (key === 0) return 0.28668068899235255
            if (key === 2) return 0.40499054814728214
            if (key === 4) return 0.4795747568909551
            if (key === 5) return 0.2951313609808264
            if (key === 6) return 0.548933174240757
            if (key === 7) return 0.3714683855083627
            if (key === 8) return 0.5913232507840008
            if (key === 9) return 0.4899147678428972
            if (key === 10) return 0.6845070422535211
            if (key === 11) return 0.4979482623892771
            if (key === 12) return 0
            if (key === 13) return 0.5571854927170444
            return 0.2866806567554743
        }
        if (kind === 2) {
            if (key === 2) return 0.26174576987682935
            if (key === 3) return 0.2951313609808264
            if (key === 4) return 0.32090071557273325
            if (key === 5) return 0.3204834736568827
            if (key === 6) return 0.42230916627695864
            if (key === 7) return 0.3796384032343475
            if (key === 8) return 0.49836550430512766
            if (key === 9) return 0.48977824466329223
            if (key === 10) return 0.5744218423332966
            if (key === 11) return 0.5573838784661092
            if (key === 12) return 0
            if (key === 13) return 0.6164982540506713
            return 0.13498520649654763
        }
        if (kind === 3) {
            if (key === 0) return 0.28668068899235255
            if (key === 2) return 0.40499054814728214
            if (key === 4) return 0.4795747568909551
            if (key === 5) return 0.2951313609808264
            if (key === 6) return 0.548933174240757
            if (key === 7) return 0.3714683855083627
            if (key === 8) return 0.5913232507840008
            if (key === 9) return 0.4899147678428972
            if (key === 10) return 0.6845070422535211
            if (key === 11) return 0.4979482623892771
            if (key === 12) return 0
            if (key === 13) return 0.5571854927170444
            return 0.2866806567554743
        }
        if (kind === 4) {
            if (key === 0) return 0.28668068899235255
            if (key === 2) return 0.40499054814728214
            if (key === 4) return 0.4795747568909551
            if (key === 5) return 0.2951313609808264
            if (key === 6) return 0.548933174240757
            if (key === 7) return 0.3714683855083627
            if (key === 8) return 0.5913232507840008
            if (key === 9) return 0.4899147678428972
            if (key === 10) return 0.6845070422535211
            if (key === 11) return 0.4979482623892771
            if (key === 12) return 0
            if (key === 13) return 0.5571854927170444
            return 0.2866806567554743
        }
        if (kind === 5) {
            if (key === 0) return 0.28668068899235255
            if (key === 2) return 0.40499054814728214
            if (key === 4) return 0.4795747568909551
            if (key === 5) return 0.2951313609808264
            if (key === 6) return 0.548933174240757
            if (key === 7) return 0.3714683855083627
            if (key === 8) return 0.5913232507840008
            if (key === 9) return 0.4899147678428972
            if (key === 10) return 0.6845070422535211
            if (key === 11) return 0.4979482623892771
            if (key === 12) return 0
            if (key === 13) return 0.5571854927170444
            return 0.2866806567554743
        }
        if (kind === 6) {
            if (key === 2) return 0.26977926442320915
            if (key === 3) return 0.31227293417487345
            if (key === 6) return 0.3380281690140845
            if (key === 7) return 0.3211267605633803
            if (key === 8) return 0.36338028169014086
            if (key === 9) return 0.37183098591549296
            if (key === 10) return 0.4563380281690141
            if (key === 11) return 0.38028169014084506
            if (key === 12) return 0
            if (key === 13) return 0.4394366197183099
            if (key === 0 || key === 1) return 0.2535211267605634
            return 0.29577464788732394
        }
        {
            if (key === 3) return 0.2782299525301221
            if (key === 7) return 0.2955485706597986
            if (key === 10) return 0.30399927488515077
            if (key === 11) return 0.34625279601191133
            if (key === 12) return 0
            if (key === 13) return 0.3464788732394366
            if (key === 0 || key === 1) return 0.19436619718309858
            if (key === 2 || key === 5) return 0.21971830985915494
            if (key === 4 || key === 9) return 0.23661971830985915
            return 0.2619718309859155
        }
    }
}

const partoverhang = (skin002: boolean, skin003: boolean, kind: number, tilt: number, right: boolean) => {
    const key = tilt * 2 + (right ? 1 : 0)
    if (skin002) {
        if (kind === 0) {
            if (key === 0) return 0.1267605684172939
            if (key === 3) return 0.10985915089996767
            if (key === 4) return 0.16901408702554838
            if (key === 5) return 0.10140844843756984
            if (key === 7) return 0.07605634105037636
            if (key === 8) return 0.1774647831916809
            if (key === 9) return 0.09295774597517202
            if (key === 10) return 0.2619718330007204
            if (key === 11) return 0.08450704351277419
            if (key === 13) return 0.1521126821007527
            if (key === 1 || key === 12) return 0
            return 0.16056337826688524
        }
        if (kind === 1) {
            if (key === 0) return 0.1267605684172939
            if (key === 3) return 0.10985915089996767
            if (key === 4) return 0.16901408702554838
            if (key === 5) return 0.10140844843756984
            if (key === 7) return 0.07605634105037636
            if (key === 8) return 0.1774647831916809
            if (key === 9) return 0.09295774597517202
            if (key === 10) return 0.2619718330007204
            if (key === 11) return 0.08450704351277419
            if (key === 13) return 0.1521126821007527
            if (key === 1 || key === 12) return 0
            return 0.16056337826688524
        }
        if (kind === 2) {
            if (key === 0) return 0.1267605684172939
            if (key === 3) return 0.10985915089996767
            if (key === 4) return 0.16901408702554838
            if (key === 5) return 0.10140844843756984
            if (key === 7) return 0.07605634105037636
            if (key === 8) return 0.1774647831916809
            if (key === 9) return 0.09295774597517202
            if (key === 10) return 0.2619718330007204
            if (key === 11) return 0.08450704351277419
            if (key === 13) return 0.1521126821007527
            if (key === 1 || key === 12) return 0
            return 0.16056337826688524
        }
        if (kind === 3) {
            if (key === 0) return 0.13521126458342647
            if (key === 2) return 0.14366197334208958
            if (key === 3) return 0.10140844843756984
            if (key === 5) return 0.06760563229171324
            if (key === 7) return 0.07605634105037636
            if (key === 10) return 0.2619718330007204
            if (key === 11) return 0.1521126821007527
            if (key === 13) return 0.1267605684172939
            if (key === 1 || key === 12) return 0
            if (key === 4 || key === 9) return 0.1183098596586308
            return 0.18591549195034404
        }
        if (kind === 4) {
            if (key === 0) return 0.13521126458342647
            if (key === 2) return 0.14366197334208958
            if (key === 3) return 0.10140844843756984
            if (key === 5) return 0.06760563229171324
            if (key === 7) return 0.07605634105037636
            if (key === 10) return 0.2619718330007204
            if (key === 11) return 0.1521126821007527
            if (key === 13) return 0.1267605684172939
            if (key === 1 || key === 12) return 0
            if (key === 4 || key === 9) return 0.1183098596586308
            return 0.18591549195034404
        }
        if (kind === 5) {
            if (key === 0) return 0.13521126458342647
            if (key === 2) return 0.14366197334208958
            if (key === 3) return 0.10140844843756984
            if (key === 5) return 0.06760563229171324
            if (key === 7) return 0.07605634105037636
            if (key === 10) return 0.2619718330007204
            if (key === 11) return 0.1521126821007527
            if (key === 13) return 0.1267605684172939
            if (key === 1 || key === 12) return 0
            if (key === 4 || key === 9) return 0.1183098596586308
            return 0.18591549195034404
        }
        if (kind === 6) {
            if (key === 8) return 0.14366197334208958
            if (key === 11) return 0.05070422421878492
            if (key === 13) return 0.03380281614585662
            if (key === 5 || key === 6) return 0.08450704351277419
            if (key === 0 || key === 3 || key === 7) return 0.07605634105037636
            if (key === 1 || key === 10 || key === 12) return 0
            return 0.10140844843756984
        }
        {
            if (key === 0) return 0.10985915089996767
            if (key === 2) return 0.1183098596586308
            if (key === 4) return 0.13521126458342647
            if (key === 6) return 0.20281689687513968
            if (key === 7) return 0.06760563229171324
            if (key === 8) return 0.1521126821007527
            if (key === 11) return 0.07605634105037636
            if (key === 3 || key === 13) return 0.09295774597517202
            if (key === 5 || key === 9) return 0.0591549298293154
            return 0
        }
    }
    if (skin003) {
        if (kind === 0) {
            if (key === 2) return 0.1267605684172939
            if (key === 5) return 0.09295774597517202
            if (key === 8) return 0.1521126821007527
            if (key === 9) return 0.1183098596586308
            if (key === 10) return 0.2619718330007204
            if (key === 13) return 0.1774647831916809
            if (key === 0 || key === 11) return 0.10985915089996767
            if (key === 1 || key === 12) return 0
            if (key === 3 || key === 7) return 0.08450704351277419
            return 0.14366197334208958
        }
        if (kind === 1) {
            if (key === 2) return 0.1267605684172939
            if (key === 5) return 0.09295774597517202
            if (key === 8) return 0.1521126821007527
            if (key === 9) return 0.1183098596586308
            if (key === 10) return 0.2619718330007204
            if (key === 13) return 0.1774647831916809
            if (key === 0 || key === 11) return 0.10985915089996767
            if (key === 1 || key === 12) return 0
            if (key === 3 || key === 7) return 0.08450704351277419
            return 0.14366197334208958
        }
        if (kind === 2) {
            if (key === 2) return 0.1267605684172939
            if (key === 5) return 0.09295774597517202
            if (key === 8) return 0.1521126821007527
            if (key === 9) return 0.1183098596586308
            if (key === 10) return 0.2619718330007204
            if (key === 13) return 0.1774647831916809
            if (key === 0 || key === 11) return 0.10985915089996767
            if (key === 1 || key === 12) return 0
            if (key === 3 || key === 7) return 0.08450704351277419
            return 0.14366197334208958
        }
        if (kind === 3) {
            if (key === 2) return 0.1267605684172939
            if (key === 5) return 0.09295774597517202
            if (key === 8) return 0.1521126821007527
            if (key === 9) return 0.1183098596586308
            if (key === 10) return 0.2619718330007204
            if (key === 13) return 0.1774647831916809
            if (key === 0 || key === 11) return 0.10985915089996767
            if (key === 1 || key === 12) return 0
            if (key === 3 || key === 7) return 0.08450704351277419
            return 0.14366197334208958
        }
        if (kind === 4) {
            if (key === 2) return 0.1267605684172939
            if (key === 5) return 0.09295774597517202
            if (key === 8) return 0.1521126821007527
            if (key === 9) return 0.1183098596586308
            if (key === 10) return 0.2619718330007204
            if (key === 13) return 0.1774647831916809
            if (key === 0 || key === 11) return 0.10985915089996767
            if (key === 1 || key === 12) return 0
            if (key === 3 || key === 7) return 0.08450704351277419
            return 0.14366197334208958
        }
        if (kind === 5) {
            if (key === 2) return 0.1267605684172939
            if (key === 5) return 0.09295774597517202
            if (key === 8) return 0.1521126821007527
            if (key === 9) return 0.1183098596586308
            if (key === 10) return 0.2619718330007204
            if (key === 13) return 0.1774647831916809
            if (key === 0 || key === 11) return 0.10985915089996767
            if (key === 1 || key === 12) return 0
            if (key === 3 || key === 7) return 0.08450704351277419
            return 0.14366197334208958
        }
        if (kind === 6) {
            if (key === 2) return 0.1267605684172939
            if (key === 5) return 0.09295774597517202
            if (key === 8) return 0.1521126821007527
            if (key === 9) return 0.1183098596586308
            if (key === 10) return 0.2619718330007204
            if (key === 13) return 0.1774647831916809
            if (key === 0 || key === 11) return 0.10985915089996767
            if (key === 1 || key === 12) return 0
            if (key === 3 || key === 7) return 0.08450704351277419
            return 0.14366197334208958
        }
        {
            if (key === 2) return -0.06760563229171324
            if (key === 3) return -0.08450704351277419
            if (key === 4) return -0.05070422421878492
            if (key === 6) return -0.02535211210939246
            if (key === 8) return -0.03380281614585662
            if (key === 13) return -0.09295774597517202
            if (key === 7 || key === 9) return -0.10140844843756984
            if (key === 0 || key === 5 || key === 11) return -0.07605634105037636
            return 0
        }
    }
    {
        if (kind === 0) {
            if (key === 2) return 0.1774647831916809
            if (key === 3) return 0.0591549298293154
            if (key === 4) return 0.16901408702554838
            if (key === 6) return 0.16056337826688524
            if (key === 7) return 0.07605634105037636
            if (key === 8) return 0.2788732505180466
            if (key === 9) return 0.09295774597517202
            if (key === 10) return 0.2619718330007204
            if (key === 13) return 0.1521126821007527
            if (key === 5 || key === 11) return 0.06760563229171324
            return 0
        }
        if (kind === 1) {
            if (key === 2) return 0.1774647831916809
            if (key === 3) return 0.0591549298293154
            if (key === 4) return 0.16901408702554838
            if (key === 6) return 0.16056337826688524
            if (key === 7) return 0.07605634105037636
            if (key === 8) return 0.2788732505180466
            if (key === 9) return 0.09295774597517202
            if (key === 10) return 0.2619718330007204
            if (key === 13) return 0.1521126821007527
            if (key === 5 || key === 11) return 0.06760563229171324
            return 0
        }
        if (kind === 2) {
            if (key === 3) return 0.16056337826688524
            if (key === 4) return 0.22816902315112905
            if (key === 5) return 0.1774647831916809
            if (key === 6) return 0.3464788702172293
            if (key === 7) return 0.20281689687513968
            if (key === 8) return 0.3211267565337705
            if (key === 11) return 0.27042252916685294
            if (key === 12) return 0
            if (key === 13) return 0.40563379375027936
            if (key === 0 || key === 1) return 0.1521126821007527
            return 0.2619718330007204
        }
        if (kind === 3) {
            if (key === 2) return 0.1774647831916809
            if (key === 3) return 0.0591549298293154
            if (key === 4) return 0.16901408702554838
            if (key === 6) return 0.16056337826688524
            if (key === 7) return 0.07605634105037636
            if (key === 8) return 0.2788732505180466
            if (key === 9) return 0.09295774597517202
            if (key === 10) return 0.2619718330007204
            if (key === 13) return 0.1521126821007527
            if (key === 5 || key === 11) return 0.06760563229171324
            return 0
        }
        if (kind === 4) {
            if (key === 2) return 0.1774647831916809
            if (key === 3) return 0.0591549298293154
            if (key === 4) return 0.16901408702554838
            if (key === 6) return 0.16056337826688524
            if (key === 7) return 0.07605634105037636
            if (key === 8) return 0.2788732505180466
            if (key === 9) return 0.09295774597517202
            if (key === 10) return 0.2619718330007204
            if (key === 13) return 0.1521126821007527
            if (key === 5 || key === 11) return 0.06760563229171324
            return 0
        }
        if (kind === 5) {
            if (key === 2) return 0.1774647831916809
            if (key === 3) return 0.0591549298293154
            if (key === 4) return 0.16901408702554838
            if (key === 6) return 0.16056337826688524
            if (key === 7) return 0.07605634105037636
            if (key === 8) return 0.2788732505180466
            if (key === 9) return 0.09295774597517202
            if (key === 10) return 0.2619718330007204
            if (key === 13) return 0.1521126821007527
            if (key === 5 || key === 11) return 0.06760563229171324
            return 0
        }
        if (kind === 6) {
            return 0
        }
        {
            return 0
        }
    }
}

export const getNativeNoteGeometry = (skin002: boolean, skin003: boolean, kind: number) => ({
    main: { h: mainmainH(skin002, skin003, kind) },
    mark: { w: mainmarkW(skin002, skin003, kind), h: mainmarkH(skin002, skin003, kind), x: mainmarkX(skin002, skin003, kind), y: mainmarkY(skin002, skin003, kind) },
    borderLeft: mainborderLeft(skin002, skin003, kind),
    borderRight: mainborderRight(skin002, skin003, kind),
})
export const getNativeNotePartGeometry = (skin002: boolean, skin003: boolean, kind: number, tilt: number, right: boolean) => ({
    w: partw(skin002, skin003, kind, tilt, right),
    h: parth(skin002, skin003, kind, tilt, right),
    x: partx(skin002, skin003, kind, tilt, right),
    y: party(skin002, skin003, kind, tilt, right),
    tightW: parttightW(skin002, skin003, kind, tilt, right),
    overhang: partoverhang(skin002, skin003, kind, tilt, right),
})
