import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

type SpriteMetrics = { w: number; h: number; x: number; y: number; tightW: number }
type PartMetrics = { tilt: number; left: SpriteMetrics; right: SpriteMetrics; leftOverhang: number; rightOverhang: number }
type BodyMetrics = {
    main: SpriteMetrics; mark: SpriteMetrics; borderLeft: number; borderRight: number; parts: PartMetrics[]
}
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const contract = JSON.parse(readFileSync(resolve(root, 'contract/native-note-geometry.json'), 'utf8')) as Record<string, BodyMetrics[]>
const kinds = ['Tap', 'Slide', 'End', 'Flick', 'FlickLeft', 'FlickRight', 'Trace', 'Node']
let output = '// Generated by scripts/generate-native-note-geometry.ts.\n\n'
const mainFields = ['mainH', 'markW', 'markH', 'markX', 'markY', 'borderLeft', 'borderRight'] as const
const partFields = ['w', 'h', 'x', 'y', 'tightW', 'overhang'] as const
function emitMetric(name: string, values: (skin: string) => number[], part: boolean): string {
    let code = `const ${name} = (skin002: boolean, skin003: boolean, kind: number${part ? ', tilt: number, right: boolean' : ''}) => {\n`
    const all = ['skin001', 'skin002', 'skin003'].flatMap(values)
    if (!all.every(Number.isFinite)) throw new Error(`${name}: invalid geometry`)
    if (all.every(value => value === all[0])) return code + `    return ${JSON.stringify(all[0])}\n}\n\n`
    if (part) code += `    const key = tilt * 2 + (right ? 1 : 0)\n`
    for (const [index, skin] of ['skin002', 'skin003', 'skin001'].entries()) {
        code += `    ${index === 2 ? '' : `if (${skin === 'skin002' ? 'skin002' : 'skin003'}) `}{\n`
        const entries = part ? Array.from({ length: 8 }, (_, kind) => values(skin).slice(kind * 14, kind * 14 + 14)) : [values(skin)]
        for (const [kind, row] of entries.entries()) {
            if (part) code += `        ${kind === 7 ? '' : `if (kind === ${kind}) `}{\n`
            const groups = new Map<number, number[]>()
            row.forEach((value, key) => groups.set(value, [...(groups.get(value) ?? []), key]))
            // A cap lookup tests at most fourteen local part keys, avoiding
            // a long cross-kind OR chain in the native compiler dataflow.
            const ordered = [...groups].sort((a, b) => a[1].length - b[1].length)
            for (const [i, [value, keys]] of ordered.entries())
                code += `        ${part ? '    ' : ''}${i === ordered.length - 1 ? '' : `if (${keys.map(key => `${part ? 'key' : 'kind'} === ${key}`).join(' || ')}) `}return ${JSON.stringify(value)}\n`
            if (part) code += '        }\n'
        }
        code += '    }\n'
    }
    return code + '}\n\n'
}
for (const field of mainFields) output += emitMetric(`main${field}`, skin => contract[skin]!.map(row => {
    if (row.parts.length !== 7) throw new Error(`${skin}: expected seven tilt parts`)
    if (field === 'mainH') return row.main.h
    if (field === 'borderLeft' || field === 'borderRight') return row[field]
    return row.mark[field === 'markW' ? 'w' : field === 'markH' ? 'h' : field === 'markX' ? 'x' : 'y']
}), false)
for (const field of partFields) output += emitMetric(`part${field}`, skin => contract[skin]!.flatMap(row => row.parts.flatMap((part, tilt) => {
    if (part.tilt !== tilt) throw new Error(`${skin}: tilt order`)
    return ['left', 'right'].map(side => field === 'overhang' ? side === 'right' ? part.rightOverhang : part.leftOverhang : part[side as 'left' | 'right'][field])
})), true)
output += `export const getNativeNoteGeometry = (skin002: boolean, skin003: boolean, kind: number) => ({\n    main: { h: mainmainH(skin002, skin003, kind) },\n    mark: { w: mainmarkW(skin002, skin003, kind), h: mainmarkH(skin002, skin003, kind), x: mainmarkX(skin002, skin003, kind), y: mainmarkY(skin002, skin003, kind) },\n    borderLeft: mainborderLeft(skin002, skin003, kind),\n    borderRight: mainborderRight(skin002, skin003, kind),\n})\n`
output += `export const getNativeNotePartGeometry = (skin002: boolean, skin003: boolean, kind: number, tilt: number, right: boolean) => ({\n${partFields.map(field => `    ${field}: part${field}(skin002, skin003, kind, tilt, right),`).join('\n')}\n})\n`
writeFileSync(resolve(root, 'shared/src/engine/data/nativeNoteGeometry.generated.ts'), output)
let sprites = '// Generated by scripts/generate-native-note-geometry.ts.\n\nexport const nativeNoteCapSprites = {\n'
for (const kind of kinds) for (const side of ['Left', 'Right']) for (let tilt = 0; tilt <= 6; tilt++)
    sprites += `    native${kind}${side}${tilt}: 'Our Notes Native ${kind} ${side} ${tilt}',\n`
for (const kind of kinds) for (const side of ['Left', 'Middle', 'Right'])
    sprites += `    native${kind}Main${side}: 'Our Notes Native ${kind} Main ${side}',\n`
sprites += '} as const\n\n'
sprites += `export const getNativeNoteCapId = (sprites: { [Key in keyof typeof nativeNoteCapSprites]: { id: SkinSpriteId } }, kind: number, tilt: number, right: boolean): SkinSpriteId => {\n`
for (const [kind, label] of kinds.entries()) {
    sprites += `    ${kind === 7 ? '' : `if (kind === ${kind}) `}{\n`
    for (let tilt = 0; tilt <= 6; tilt++)
        sprites += `        ${tilt === 6 ? '' : `if (tilt === ${tilt}) `}return right ? sprites.native${label}Right${tilt}.id : sprites.native${label}Left${tilt}.id\n`
    sprites += '    }\n'
}
sprites += '}\n'
sprites += `const mainId = (sprites: { [Key in keyof typeof nativeNoteCapSprites]: { id: SkinSpriteId } }, kind: number, part: number): SkinSpriteId => {\n`
for (const [kind, label] of kinds.entries())
    sprites += `    ${kind === 7 ? '' : `if (kind === ${kind}) `}return part === 0 ? sprites.native${label}MainLeft.id : part === 1 ? sprites.native${label}MainMiddle.id : sprites.native${label}MainRight.id\n`
sprites += '}\n'
sprites += `export const getNativeNoteMainIds = (sprites: { [Key in keyof typeof nativeNoteCapSprites]: { id: SkinSpriteId } }, kind: number) => ({ left: mainId(sprites, kind, 0), middle: mainId(sprites, kind, 1), right: mainId(sprites, kind, 2) })\n`
writeFileSync(resolve(root, 'shared/src/engine/data/nativeNoteSprites.generated.ts'), sprites)

// Tutorials display a fixed centred size=2 note. Precompute that authored
// pose so runtime/compiler work is limited to choosing its selected skin.
const tutorialFields = ['leftL', 'leftR', 'capB', 'capT', 'mainL', 'mainInnerL', 'mainInnerR', 'mainR', 'mainB', 'mainT', 'markL', 'markR', 'markB', 'markT'] as const
const tutorialRows = Object.fromEntries(Object.entries(contract).map(([skin, rows]) => [skin, rows.map(row => {
    const cap = row.parts[2]!.right
    const overhang = row.parts[2]!.rightOverhang
    const capCenter = -2 + cap.tightW / 2 - overhang - cap.x
    const mainHalfWidth = Math.max(0.001, 4 - cap.tightW * 2 + overhang * 2) / 2
    const borderTotal = row.borderLeft + row.borderRight
    const borderScale = borderTotal > mainHalfWidth * 2 ? mainHalfWidth * 2 / borderTotal : 1
    return [capCenter + cap.w / 2, capCenter - cap.w / 2, 1 - cap.y + cap.h, 1 - cap.y - cap.h,
        -mainHalfWidth, -mainHalfWidth + row.borderLeft * borderScale, mainHalfWidth - row.borderRight * borderScale, mainHalfWidth,
        1 + row.main.h, 1 - row.main.h, row.mark.x - row.mark.w / 2, row.mark.x + row.mark.w / 2,
        1 - row.mark.y + row.mark.h, 1 - row.mark.y - row.mark.h]
})]))
let tutorial = '// Generated fixed centred tutorial pose; size=2.\n\n'
for (const [index, field] of tutorialFields.entries())
    tutorial += emitMetric(`tutorial${field}`, skin => tutorialRows[skin]!.map(row => row[index]!), false)
tutorial += `export const getNativeTutorialNoteRects = (kind: number, skin002: boolean, skin003: boolean) => {\n`
for (const field of tutorialFields) tutorial += `    const ${field} = tutorial${field}(skin002, skin003, kind)\n`
tutorial += `    return {\n        left: { l: leftL, r: leftR, b: capB, t: capT },\n        mainLeft: { l: mainL, r: mainInnerL, b: mainB, t: mainT },\n        middle: { l: mainInnerL, r: mainInnerR, b: mainB, t: mainT },\n        mainRight: { l: mainInnerR, r: mainR, b: mainB, t: mainT },\n        right: { l: -leftL, r: -leftR, b: capB, t: capT },\n        mark: { l: markL, r: markR, b: markB, t: markT },\n    }\n}\n`
writeFileSync(resolve(root, 'shared/src/engine/data/nativeTutorialGeometry.generated.ts'), tutorial)
