import { SkinSpriteName } from '@sonolus/core'

export const skin = defineSkin({
    sprites: {
        sekaiStage: 'Our Notes Stage',
        laneTapArea: 'Our Notes Lane Tap Area',
        laneTapAreaTopLeft: 'Our Notes Lane Tap Area Top Left',
        laneTapAreaTop: 'Our Notes Lane Tap Area Top',
        laneTapAreaTopRight: 'Our Notes Lane Tap Area Top Right',
        laneTapAreaLeft: 'Our Notes Lane Tap Area Left',
        laneTapAreaCenter: 'Our Notes Lane Tap Area Center',
        laneTapAreaRight: 'Our Notes Lane Tap Area Right',
        laneTapAreaBottomLeft: 'Our Notes Lane Tap Area Bottom Left',
        laneTapAreaBottom: 'Our Notes Lane Tap Area Bottom',
        laneTapAreaBottomRight: 'Our Notes Lane Tap Area Bottom Right',
        guideline: 'Our Notes Guideline',
        guidelineSpace: 'Our Notes Guideline Space',
        outsideLine: 'Our Notes Outside Line',
        nativeJudgmentLine: 'Our Notes Judgment Line',

        simLine: 'Our Notes Simultaneous Line',
        normalNoteLeft: 'Our Notes Note Cyan Left',
        normalNoteMiddle: 'Our Notes Note Cyan Middle',
        normalNoteRight: 'Our Notes Note Cyan Right',
        normalNoteFallback: SkinSpriteName.NoteHeadCyan,

        slideNoteLeft: 'Our Notes Note Green Left',
        slideNoteMiddle: 'Our Notes Note Green Middle',
        slideNoteRight: 'Our Notes Note Green Right',
        slideNoteFallback: SkinSpriteName.NoteHeadGreen,
        slideNoteEndFallback: SkinSpriteName.NoteTailGreen,

        slideEndNoteLeft: 'Our Notes Note Green End Left',
        slideEndNoteMiddle: 'Our Notes Note Green End Middle',
        slideEndNoteRight: 'Our Notes Note Green End Right',

        flickNoteLeft: 'Our Notes Note Red Left',
        flickNoteMiddle: 'Our Notes Note Red Middle',
        flickNoteRight: 'Our Notes Note Red Right',
        flickNoteFallback: SkinSpriteName.NoteHeadRed,
        flickNoteEndFallback: SkinSpriteName.NoteTailRed,

        flickLeftNoteLeft: 'Our Notes Note Red Leftward Left',
        flickLeftNoteMiddle: 'Our Notes Note Red Leftward Middle',
        flickLeftNoteRight: 'Our Notes Note Red Leftward Right',
        flickRightNoteLeft: 'Our Notes Note Red Rightward Left',
        flickRightNoteMiddle: 'Our Notes Note Red Rightward Middle',
        flickRightNoteRight: 'Our Notes Note Red Rightward Right',

        tapDecoration: 'Our Notes Tap Decoration',
        slideDecoration: 'Our Notes Slide Decoration',
        flickDecoration: 'Our Notes Flick Decoration',
        flickLeftDecoration: 'Our Notes Flick Left Decoration',
        flickRightDecoration: 'Our Notes Flick Right Decoration',

        criticalNoteLeft: 'Our Notes Note Yellow Left',
        criticalNoteMiddle: 'Our Notes Note Yellow Middle',
        criticalNoteRight: 'Our Notes Note Yellow Right',
        criticalNoteFallback: SkinSpriteName.NoteHeadYellow,
        criticalNoteEndFallback: SkinSpriteName.NoteTailYellow,

        normalSlideTickNote: 'Our Notes Diamond Green',
        normalSlideTickNoteFallback: SkinSpriteName.NoteTickGreen,

        criticalSlideTickNote: 'Our Notes Diamond Yellow',
        criticalSlideTickNoteFallback: SkinSpriteName.NoteTickYellow,

        traceFlickNote: 'Our Notes Trace Note Red',
        traceFlickNoteLeft: 'Our Notes Trace Note Red Left',
        traceFlickNoteMiddle: 'Our Notes Trace Note Red Middle',
        traceFlickNoteRight: 'Our Notes Trace Note Red Right',
        traceFlickNoteDiamond: 'Our Notes Trace Diamond Red',
        traceFlickNoteFallback: SkinSpriteName.NoteTickRed,

        normalTraceNote: 'Our Notes Trace Note Green',
        normalTraceNoteLeft: 'Our Notes Trace Note Green Left',
        normalTraceNoteMiddle: 'Our Notes Trace Note Green Middle',
        normalTraceNoteRight: 'Our Notes Trace Note Green Right',
        normalTraceNoteDiamond: 'Our Notes Trace Diamond Green',
        normalTraceNoteFallback: SkinSpriteName.NoteTickGreen,

        criticalTraceNote: 'Our Notes Trace Note Yellow',
        criticalTraceNoteLeft: 'Our Notes Trace Note Yellow Left',
        criticalTraceNoteMiddle: 'Our Notes Trace Note Yellow Middle',
        criticalTraceNoteRight: 'Our Notes Trace Note Yellow Right',
        criticalTraceNoteDiamond: 'Our Notes Trace Diamond Yellow',
        criticalTraceNoteFallback: SkinSpriteName.NoteTickYellow,

        normalSlideConnectorNormal: 'Our Notes Slide Connection Green',
        normalSlideConnectorActive: 'Our Notes Slide Connection Green Active',
        normalSlideConnectorFallback: SkinSpriteName.NoteConnectionGreenSeamless,

        criticalSlideConnectorNormal: 'Our Notes Slide Connection Yellow',
        criticalSlideConnectorActive: 'Our Notes Slide Connection Yellow Active',
        criticalSlideConnectorFallback: SkinSpriteName.NoteConnectionYellowSeamless,

        normalActiveSlideConnectorNormal: 'Our Notes Active Slide Connection Green',
        normalActiveSlideConnectorActive: 'Our Notes Active Slide Connection Green Active',
        normalActiveSlideConnectorFallback: SkinSpriteName.NoteConnectionGreenSeamless,

        criticalActiveSlideConnectorNormal: 'Our Notes Active Slide Connection Yellow',
        criticalActiveSlideConnectorActive: 'Our Notes Active Slide Connection Yellow Active',
        criticalActiveSlideConnectorFallback: SkinSpriteName.NoteConnectionYellowSeamless,

        normalSlotGlow: 'Our Notes Slot Glow Cyan',
        slideSlotGlow: 'Our Notes Slot Glow Green',
        flickSlotGlow: 'Our Notes Slot Glow Red',
        criticalSlotGlow: 'Our Notes Slot Glow Yellow',

        normalSlot: 'Our Notes Slot Cyan',
        slideSlot: 'Our Notes Slot Green',
        flickSlot: 'Our Notes Slot Red',
        criticalSlot: 'Our Notes Slot Yellow',

        flickArrowUp1: 'Our Notes Flick Arrow Red Up 1',
        flickArrowUp2: 'Our Notes Flick Arrow Red Up 2',
        flickArrowUp3: 'Our Notes Flick Arrow Red Up 3',
        flickArrowUp4: 'Our Notes Flick Arrow Red Up 4',
        flickArrowUp5: 'Our Notes Flick Arrow Red Up 5',
        flickArrowUp6: 'Our Notes Flick Arrow Red Up 6',
        flickArrowUp7: 'Our Notes Flick Arrow Red Up 7',
        flickArrowUp8: 'Our Notes Flick Arrow Red Up 8',
        flickArrowLeft1: 'Our Notes Flick Arrow Red Left 1',
        flickArrowLeft2: 'Our Notes Flick Arrow Red Left 2',
        flickArrowLeft3: 'Our Notes Flick Arrow Red Left 3',
        flickArrowLeft4: 'Our Notes Flick Arrow Red Left 4',
        flickArrowLeft5: 'Our Notes Flick Arrow Red Left 5',
        flickArrowLeft6: 'Our Notes Flick Arrow Red Left 6',
        flickArrowLeft7: 'Our Notes Flick Arrow Red Left 7',
        flickArrowLeft8: 'Our Notes Flick Arrow Red Left 8',
        flickArrowRight1: 'Our Notes Flick Arrow Red Right 1',
        flickArrowRight2: 'Our Notes Flick Arrow Red Right 2',
        flickArrowRight3: 'Our Notes Flick Arrow Red Right 3',
        flickArrowRight4: 'Our Notes Flick Arrow Red Right 4',
        flickArrowRight5: 'Our Notes Flick Arrow Red Right 5',
        flickArrowRight6: 'Our Notes Flick Arrow Red Right 6',
        flickArrowRight7: 'Our Notes Flick Arrow Red Right 7',
        flickArrowRight8: 'Our Notes Flick Arrow Red Right 8',
        flickArrowFallback: SkinSpriteName.DirectionalMarkerRed,

        criticalArrowUp1: 'Our Notes Flick Arrow Yellow Up 1',
        criticalArrowUp2: 'Our Notes Flick Arrow Yellow Up 2',
        criticalArrowUp3: 'Our Notes Flick Arrow Yellow Up 3',
        criticalArrowUp4: 'Our Notes Flick Arrow Yellow Up 4',
        criticalArrowUp5: 'Our Notes Flick Arrow Yellow Up 5',
        criticalArrowUp6: 'Our Notes Flick Arrow Yellow Up 6',
        criticalArrowUp7: 'Our Notes Flick Arrow Yellow Up 7',
        criticalArrowUp8: 'Our Notes Flick Arrow Yellow Up 8',
        criticalArrowLeft1: 'Our Notes Flick Arrow Yellow Left 1',
        criticalArrowLeft2: 'Our Notes Flick Arrow Yellow Left 2',
        criticalArrowLeft3: 'Our Notes Flick Arrow Yellow Left 3',
        criticalArrowLeft4: 'Our Notes Flick Arrow Yellow Left 4',
        criticalArrowLeft5: 'Our Notes Flick Arrow Yellow Left 5',
        criticalArrowLeft6: 'Our Notes Flick Arrow Yellow Left 6',
        criticalArrowLeft7: 'Our Notes Flick Arrow Yellow Left 7',
        criticalArrowLeft8: 'Our Notes Flick Arrow Yellow Left 8',
        criticalArrowRight1: 'Our Notes Flick Arrow Yellow Right 1',
        criticalArrowRight2: 'Our Notes Flick Arrow Yellow Right 2',
        criticalArrowRight3: 'Our Notes Flick Arrow Yellow Right 3',
        criticalArrowRight4: 'Our Notes Flick Arrow Yellow Right 4',
        criticalArrowRight5: 'Our Notes Flick Arrow Yellow Right 5',
        criticalArrowRight6: 'Our Notes Flick Arrow Yellow Right 6',
        criticalArrowRight7: 'Our Notes Flick Arrow Yellow Right 7',
        criticalArrowRight8: 'Our Notes Flick Arrow Yellow Right 8',
        criticalArrowFallback: SkinSpriteName.DirectionalMarkerYellow,
    },
})

export const layer = {
    note: {
        arrow: 102,
        tick: 101,
        body: 100,
        trace: 99,
        slide: 98,
        connector: 97,
    },

    simLine: 90,

    tapArea: 2,
    guideline: 1,
    stage: 0,
}

export const getZ = (layer: number, time: number, lane: number) =>
    layer - time / 1000 - lane / 100000
